{
 "title": "dotnet",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(NgsaAppDuration_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_collection_count_total{job!=\"kubernetes-pods\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job!=\"kubernetes-pods\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job!~\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{job!~\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job!~\"kubernetes-pods\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "ngsa",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_bucket[1m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "ngsa.app",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{mode != \"Metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "LodeRunner",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(LodeRunnerDuration_count[1m]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(NgsaAppDuration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_bucket{code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}